# Generated by Django 5.1.8 on 2025-04-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rchoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='event',
        ),
        migrations.RemoveField(
            model_name='application',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
