services:
  docs:
    image: s_angel_local_docs
    container_name: s_angel_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./s_angel:/app/s_angel:z
    ports:
      - '9000:9000'
    command: /start-docs
