# Generated by Django 5.1.8 on 2025-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='User Weight'),
        ),
    ]
