# Generated by Django 5.1.8 on 2026-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_accounting',
            field=models.BooleanField(default=False, verbose_name='회계 열람 권한'),
        ),
        migrations.AddField(
            model_name='user',
            name='generation',
            field=models.PositiveIntegerField(default=21, verbose_name='기수'),
        ),
    ]
