# Generated by Django 5.1.8 on 2025-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
