# Generated by Django 5.1.8 on 2026-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
