# Generated by Django 5.1.8 on 2026-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_event_is_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('item_name', models.CharField(max_length=100, verbose_name='항목명')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('transaction_type', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], max_length=10, verbose_name='구분')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
