# Generated by Django 5.1.8 on 2026-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정 제목')),
                ('content', models.TextField(blank=True, verbose_name='상세 내용')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료 날짜')),
                ('color', models.CharField(default='#1E3A8A', max_length=20, verbose_name='색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
