# Generated by Django 5.1.8 on 2026-01-09 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_clubschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubschedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='clubschedule',
            name='start_date',
        ),
        migrations.AddField(
            model_name='clubschedule',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료 일시'),
        ),
        migrations.AddField(
            model_name='clubschedule',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작 일시'),
            preserve_default=False,
        ),
    ]
