# Generated by Django 5.1.8 on 2026-01-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_clubschedule_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='행사명')),
                ('date', models.DateField(verbose_name='대표 날짜')),
                ('description', models.TextField(blank=True, verbose_name='행사 설명')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='연도(기수)')),
                ('is_active', models.BooleanField(default=False, verbose_name='현재 활성 기수')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='applications.accountingevent'),
        ),
        migrations.AddField(
            model_name='accountingevent',
            name='budget_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.budgetyear'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='budget_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_transactions', to='applications.budgetyear'),
        ),
    ]
