# Generated by Django 5.1.8 on 2026-08-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_accountingevent_budgetyear_transaction_event_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialLotteryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="특별추첨명"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="설명"),
                ),
                (
                    "draw_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "가중치 반영 + 반복 선발 완화"),
                            ("WEIGHTED", "기존 가중치 그대로 반영"),
                            ("EQUAL", "모든 신청자 동일 확률"),
                        ],
                        default="BALANCED",
                        max_length=20,
                        verbose_name="임시 추첨 방식",
                    ),
                ),
                (
                    "is_drawn",
                    models.BooleanField(default=False, verbose_name="임시 추첨 완료"),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, verbose_name="최종 확정"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_special_lotteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="special_lottery_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="applications.speciallotterygroup",
                verbose_name="특별추첨 묶음",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="special_lottery_order",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="특별추첨 내 순서",
            ),
        ),
        migrations.CreateModel(
            name="SpecialLotterySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_count", models.PositiveIntegerField()),
                ("selected_count", models.PositiveIntegerField()),
                ("total_application_count", models.PositiveIntegerField()),
                ("total_selected_count", models.PositiveIntegerField()),
                ("previous_weight", models.PositiveIntegerField()),
                ("new_weight", models.PositiveIntegerField()),
                (
                    "adjustment",
                    models.CharField(
                        choices=[
                            ("INCREASE", "가중치 증가"),
                            ("KEEP", "가중치 유지"),
                            ("RESET", "가중치 초기화"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="applications.speciallotterygroup",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_lottery_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["participant_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="speciallotterysettlement",
            constraint=models.UniqueConstraint(
                fields=("group", "participant"),
                name="unique_special_lottery_settlement",
            ),
        ),
    ]
